version: '3'

services:
  app:
    build: .
    image: takacsmark/flask-redis:1.0
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000

  redis:
    image: redis:4.0.11-alpine

    # Run
    # docker-compose up -d
    
    # Check
    # curl --header "Content-Type: application/json" \
    #      --request POST \
    #      --data '{"name":"Kumar"}' \
    #      $(docker-machine ip Char):5000