FROM debian

MAINTAINER nrepak <nazara.re22@gmail.com>

RUN apt-get update && apt-get install -y \ 
    build-essential \
	vim \
    git

# docker build -t bonus/ex00 .
# docker run --rm -ti bonus/ex00

