FROM ubuntu

MAINTAINER nrepak <nazara.re22@gmail.com>

RUN apt-get update && apt-get install -y \
	git \
	vim \
	nodejs \
	npm

RUN npm install yarn --global

# docker build -t bonus/ex00 .
# docker run --rm -ti bonus/ex00
